/**
 * 玩法侧玩家可见文本的 key 一览（conventions 规则 4: 文案零硬编码）。
 * systems は key のみを参照（文案を知らない）。中文/英文文案表は systems/i18n/zhTable.ts・
 * enTable.ts、查表は systems/i18n の TextProvider（S-11 落地済み）。
 * ui/ からも本モジュールの key を参照する（依存方向: ui → 共通 → systems を崩さないため
 * key 定数だけを这里に置く — systems が ui/ を import しない）。
 */
export const TEXT_KEYS = {
  // 晨间（S-05 排班）
  MORNING_TITLE: 'morning.title',
  MORNING_HINT_SELECT_POST: 'morning.hint.selectPost',
  MORNING_HINT_SELECT_STAFF: 'morning.hint.selectStaff',
  NOTICE_ASSIGN_REJECTED: 'morning.notice.assignRejected',
  BUTTON_OPEN_DOOR: 'morning.button.openDoor',
  POST_WAITER: 'post.waiter',
  POST_MANAGER: 'post.manager',
  POST_PURCHASER: 'post.purchaser',
  POST_TRAINING: 'post.training',
  POST_STANDBY: 'post.standby',
  // 日间（S-06 接客）
  LABEL_COUNTER: 'day.label.counter',
  LABEL_SERVE_WINDOW: 'day.label.serveWindow',
  BUBBLE_ORDER: 'day.bubble.order',
  BUBBLE_PAYMENT: 'day.bubble.payment',
  // 夜间（S-09 结算与事件卡）
  NIGHT_TITLE: 'night.title',
  SUMMARY_INCOME: 'night.summary.income',
  SUMMARY_REP_NET: 'night.summary.repNet',
  SUMMARY_SERVED: 'night.summary.served',
  SUMMARY_FAILED: 'night.summary.failed',
  SUMMARY_WAGE: 'night.summary.wage',
  BUTTON_DRAW_CARD: 'night.button.draw',
  CARD_TITLE_LABEL: 'night.card.title',
  CARD_RESULT_LABEL: 'night.card.result',
  BUTTON_DAYBREAK: 'night.button.daybreak',
  BUTTON_FIGHT: 'night.button.fight',
  FINAL_BATTLE_NOTICE: 'night.finalBattleNotice',
  // 伙计名（gdd「伙计初始值」5 名）
  STAFF_AFU: 'staff.afu',
  STAFF_TIENIU: 'staff.tieniu',
  STAFF_WENQU: 'staff.wenqu',
  STAFF_XIAODIE: 'staff.xiaodie',
  STAFF_DASONG: 'staff.dasong',
  // 成长阶段別台词（S-07: 台词按成长阶段切换）
  STAFF_LINE_STAGE_1: 'staff.line.stage1',
  STAFF_LINE_STAGE_2: 'staff.line.stage2',
  STAFF_LINE_STAGE_3: 'staff.line.stage3',
  // 事件卡（垂直切片 3 张 — gdd「事件卡」表の #1/#5/#8。build S-17 で 15 张に拡張）
  CARD_1_TITLE: 'card.1.title',
  CARD_1_OPT1: 'card.1.opt1',
  CARD_1_OPT1_RESULT: 'card.1.opt1.result',
  CARD_1_OPT2: 'card.1.opt2',
  CARD_1_OPT2_RESULT: 'card.1.opt2.result',
  CARD_5_TITLE: 'card.5.title',
  CARD_5_OPT1: 'card.5.opt1',
  CARD_5_OPT1_RESULT: 'card.5.opt1.result',
  CARD_5_OPT2: 'card.5.opt2',
  CARD_5_OPT2_RESULT: 'card.5.opt2.result',
  CARD_8_TITLE: 'card.8.title',
  CARD_8_OPT1: 'card.8.opt1',
  CARD_8_OPT1_RESULT: 'card.8.opt1.result',
  CARD_8_OPT2: 'card.8.opt2',
  CARD_8_OPT2_RESULT: 'card.8.opt2.result',
  // 事件卡（build S-17: 全 15 张 — gdd「事件卡」表の #2/#3/#4/#6/#7/#9/#10/#11/#12/#13/#14/#15。
  // #2 と #15 は 3 选项、他は 2 选项）
  CARD_2_TITLE: 'card.2.title',
  CARD_2_OPT1: 'card.2.opt1',
  CARD_2_OPT1_RESULT: 'card.2.opt1.result',
  CARD_2_OPT2: 'card.2.opt2',
  CARD_2_OPT2_RESULT: 'card.2.opt2.result',
  CARD_2_OPT3: 'card.2.opt3',
  CARD_2_OPT3_RESULT: 'card.2.opt3.result',
  CARD_3_TITLE: 'card.3.title',
  CARD_3_OPT1: 'card.3.opt1',
  CARD_3_OPT1_RESULT: 'card.3.opt1.result',
  CARD_3_OPT2: 'card.3.opt2',
  CARD_3_OPT2_RESULT: 'card.3.opt2.result',
  CARD_4_TITLE: 'card.4.title',
  CARD_4_OPT1: 'card.4.opt1',
  CARD_4_OPT1_RESULT: 'card.4.opt1.result',
  CARD_4_OPT2: 'card.4.opt2',
  CARD_4_OPT2_RESULT: 'card.4.opt2.result',
  CARD_6_TITLE: 'card.6.title',
  CARD_6_OPT1: 'card.6.opt1',
  CARD_6_OPT1_RESULT: 'card.6.opt1.result',
  CARD_6_OPT2: 'card.6.opt2',
  CARD_6_OPT2_RESULT: 'card.6.opt2.result',
  CARD_7_TITLE: 'card.7.title',
  CARD_7_OPT1: 'card.7.opt1',
  CARD_7_OPT1_RESULT: 'card.7.opt1.result',
  CARD_7_OPT2: 'card.7.opt2',
  CARD_7_OPT2_RESULT: 'card.7.opt2.result',
  CARD_9_TITLE: 'card.9.title',
  CARD_9_OPT1: 'card.9.opt1',
  CARD_9_OPT1_RESULT: 'card.9.opt1.result',
  CARD_9_OPT2: 'card.9.opt2',
  CARD_9_OPT2_RESULT: 'card.9.opt2.result',
  CARD_10_TITLE: 'card.10.title',
  CARD_10_OPT1: 'card.10.opt1',
  CARD_10_OPT1_RESULT: 'card.10.opt1.result',
  CARD_10_OPT2: 'card.10.opt2',
  CARD_10_OPT2_RESULT: 'card.10.opt2.result',
  CARD_11_TITLE: 'card.11.title',
  CARD_11_OPT1: 'card.11.opt1',
  CARD_11_OPT1_RESULT: 'card.11.opt1.result',
  CARD_11_OPT2: 'card.11.opt2',
  CARD_11_OPT2_RESULT: 'card.11.opt2.result',
  CARD_12_TITLE: 'card.12.title',
  CARD_12_OPT1: 'card.12.opt1',
  CARD_12_OPT1_RESULT: 'card.12.opt1.result',
  CARD_12_OPT2: 'card.12.opt2',
  CARD_12_OPT2_RESULT: 'card.12.opt2.result',
  CARD_13_TITLE: 'card.13.title',
  CARD_13_OPT1: 'card.13.opt1',
  CARD_13_OPT1_RESULT: 'card.13.opt1.result',
  CARD_13_OPT2: 'card.13.opt2',
  CARD_13_OPT2_RESULT: 'card.13.opt2.result',
  CARD_14_TITLE: 'card.14.title',
  CARD_14_OPT1: 'card.14.opt1',
  CARD_14_OPT1_RESULT: 'card.14.opt1.result',
  CARD_14_OPT2: 'card.14.opt2',
  CARD_14_OPT2_RESULT: 'card.14.opt2.result',
  CARD_15_TITLE: 'card.15.title',
  CARD_15_OPT1: 'card.15.opt1',
  CARD_15_OPT1_RESULT: 'card.15.opt1.result',
  CARD_15_OPT2: 'card.15.opt2',
  CARD_15_OPT2_RESULT: 'card.15.opt2.result',
  CARD_15_OPT3: 'card.15.opt3',
  CARD_15_OPT3_RESULT: 'card.15.opt3.result',
  // 志向选择（S-04: 财/侠/名 3 按钮）
  AMBITION_TITLE: 'ambition.title',
  AMBITION_HINT: 'ambition.hint',
  AMBITION_WEALTH_LABEL: 'ambition.wealth.label',
  AMBITION_XIA_LABEL: 'ambition.xia.label',
  AMBITION_FAME_LABEL: 'ambition.fame.label',
} as const;

// ==== HUD / Result / Title / Menu 側 key（S-11: 全 key を共通層に集約 — systems/i18n の
// 言語表が参照する。ui/hudStrings は本モジュールからの re-export に切り替え）====

/** 玩家可见文本 key（HUD 与暂停面板 — S-10） */
export const HUD_TEXT_KEYS = {
  HUD_SILVER: 'hud.silver',
  HUD_REPUTATION: 'hud.reputation',
  HUD_DAY: 'hud.day',
  HUD_LEDGER: 'hud.ledger',
  PAUSE_TITLE: 'pause.title',
  PAUSE_RESUME: 'pause.resume',
  PAUSE_END_RUN: 'pause.endRun',
  PAUSE_QUIT: 'pause.quit',
} as const;

/** 玩家可见文本 key（Result 场景 — S-15） */
export const RESULT_TEXT_KEYS = {
  RESULT_TITLE_DEFEAT: 'result.title.defeat',
  RESULT_TITLE_COMPLETE: 'result.title.complete',
  RESULT_SCORE_LABEL: 'result.score',
  RESULT_SCORE_SILVER: 'result.score.silver',
  RESULT_SCORE_REPUTATION: 'result.score.reputation',
  RESULT_SCORE_POWER: 'result.score.power',
  RESULT_SCORE_BONUS: 'result.score.bonus',
  RESULT_RETRY: 'result.retry',
  RESULT_TO_MENU: 'result.toMenu',
  // ==== S-25: Result 结局演出完整版（结局文/败局专属文案/新纪录标记）====
  RESULT_TITLE_BANKRUPTCY: 'result.title.bankruptcy',
  RESULT_TITLE_FINAL_LOSS: 'result.title.finalBattleLoss',
  RESULT_BODY_BANKRUPTCY: 'result.body.bankruptcy',
  RESULT_BODY_FINAL_LOSS: 'result.body.finalBattleLoss',
  RESULT_ENDING_WEALTH_TITLE: 'result.ending.wealth.title',
  RESULT_ENDING_WEALTH_BODY: 'result.ending.wealth.body',
  RESULT_ENDING_XIA_TITLE: 'result.ending.xia.title',
  RESULT_ENDING_XIA_BODY: 'result.ending.xia.body',
  RESULT_ENDING_FAME_TITLE: 'result.ending.fame.title',
  RESULT_ENDING_FAME_BODY: 'result.ending.fame.body',
  RESULT_NEW_RECORD: 'result.newRecord',
} as const;

/** 玩家可见文本 key（Title 场景 — S-12） */
export const TITLE_TEXT_KEYS = {
  TITLE_GAME_TITLE: 'title.gameTitle',
  TITLE_START_PROMPT: 'title.startPrompt',
  TITLE_RECOVERED_NOTICE: 'title.recovered',
} as const;

/** 玩家可见文本 key（Menu 场景 — S-13 必需要素 4 项 + S-11 语言切换） */
export const MENU_TEXT_KEYS = {
  MENU_TITLE: 'menu.title',
  MENU_CONTINUE: 'menu.continue',
  MENU_NEW_RUN: 'menu.newRun',
  MENU_OPEN_STATS: 'menu.openStats',
  MENU_OPEN_SETTINGS: 'menu.openSettings',
  MENU_BACK_TITLE: 'menu.backTitle',
  MENU_RECOVERED_NOTICE: 'menu.recovered',
  MENU_STATS_TITLE: 'menu.stats.title',
  MENU_STATS_BEST: 'menu.stats.best',
  MENU_STATS_RUNS: 'menu.stats.runs',
  MENU_STATS_SILVER_PEAK: 'menu.stats.silverPeak',
  MENU_STATS_REP_PEAK: 'menu.stats.repPeak',
  MENU_STATS_SERVED: 'menu.stats.served',
  MENU_STATS_ENDINGS: 'menu.stats.endings',
  MENU_CLOSE: 'menu.close',
  MENU_SETTINGS_TITLE: 'menu.settings.title',
  MENU_BGM_LABEL: 'menu.settings.bgm',
  MENU_SFX_LABEL: 'menu.settings.sfx',
  MENU_LANGUAGE_LABEL: 'menu.settings.language',
  MENU_HINT_TITLE: 'menu.settings.hint.title',
  MENU_HINT_BODY: 'menu.settings.hint.body',
  // ==== S-26: 游戏外面板完整版（图鉴/成就/统计 3 节。结局名 ACH-01～03 は
  // RESULT_TEXT_KEYS.RESULT_ENDING_*_TITLE を再利用 — 第二定義を禁止）====
  MENU_PANEL_GALLERY_TITLE: 'menu.panel.galleryTitle',
  MENU_PANEL_ACHIEVEMENTS_TITLE: 'menu.panel.achievementsTitle',
  MENU_PANEL_STATS_TITLE: 'menu.panel.statsTitle',
  MENU_PANEL_ACH04_LABEL: 'menu.panel.ach04Label',
  MENU_PANEL_ACH05_LABEL: 'menu.panel.ach05Label',
  MENU_PANEL_ACH06_LABEL: 'menu.panel.ach06Label',
  MENU_PANEL_ACH_DONE: 'menu.panel.achDone',
  MENU_PANEL_ACH_LOCKED: 'menu.panel.achLocked',
  MENU_PANEL_SLOT_LOCKED: 'menu.panel.slotLocked',
} as const;
